import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ai-education-platform",
  description: "Generated by NoA Vibe Coding",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
